### ISSUE TITLE
Body styles

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/cloud-vanilla-theme#11]
Should be:
```css
body {
	background: url("//assets.ubuntu.com/v1/f8a323a7-image-background-paper.png") repeat-y center top #f7f7f7;
	background-size: cover;
}
```
